import torch
from transformers import AutoConfig, AutoTokenizer, AutoModelForCausalLM
from huggingface_hub import login
from datasets import load_dataset

import json
import argparse
from pathlib import Path
from tqdm import tqdm
import copy
import nltk
from typing import List, Dict, Tuple
import re
import os
from dotenv import load_dotenv

from cad import CAD

input_key = {
    "xsum": "document",
    "cnn_dm": "article",
    "ccsum": "article"
}

output_key = {
    "xsum": "summary",
    "cnn_dm": "highlights",
    "ccsum": "summary"
}

def load_model_and_tokenzier(model_name="meta-llama/Llama-3.1-8B-Instruct", cache_dir="/mnt/ssd/llms"):
    tokenizer = AutoTokenizer.from_pretrained(model_name,
                                              cache_dir=cache_dir)
    model = AutoModelForCausalLM.from_pretrained(model_name,
                                                 torch_dtype=torch.bfloat16,
                                                 device_map="auto",
                                                 cache_dir=cache_dir,
                                                 )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    return model, tokenizer

def load_data(args):
    # Load test data
    # if args.attr_data_path:
    #     with open(args.attr_data_path, "r") as fin:
    #         test_data = json.load(fin)
    #         test_data = test_data[:args.num_samples]
    # else:
    if args.dataset == "xsum":
        test_data = load_dataset("xsum", split="test")
    elif args.dataset == "cnn_dm":
        test_data = load_dataset('cnn_dailymail', '3.0.0', split='test')
    elif args.dataset == "ccsum":
        # load CCSum test data (abstractive subset)
        ccsum_dataset = load_dataset("/mnt/ceph_rbd/datasets/ccsum")
        dataset_abstractive = ccsum_dataset.filter(lambda x: x["abstractiveness_bin"] == "high")
        test_data = dataset_abstractive['test']
        
        test_data = test_data.select(range(min(args.num_samples, len(test_data))))
    
    return test_data

def split_into_sentences(text: str) -> Tuple[List[str], List[str]]:
    lines = text.splitlines()
    sentences = []
    for line in lines:
        sentences.extend(nltk.sent_tokenize(line))
    separators = []
    cur_start = 0
    for sentence in sentences:
        cur_end = text.find(sentence, cur_start)
        separators.append(text[cur_start:cur_end])
        cur_start = cur_end + len(sentence)
    return sentences, separators

def extract_sentences_and_summary(text):
    """
    Extract key sentences and summary from LLM output.
    
    Args:
        text (str): The LLM output text containing key sentences and summary
        
    Returns:
        tuple: (list of key sentences, summary string)
    """
    # Split the text to separate key sentences and summary sections
    try:
        # Find the sections
        key_sentences_start = text.find("Key Sentences:")
        summary_start = text.find("Summary:", key_sentences_start)
        
        if key_sentences_start == -1 or summary_start == -1:
            return [], ""
        
        # Extract the key sentences section
        key_sentences_text = text[key_sentences_start + len("Key Sentences:"):summary_start].strip()
        
        # Extract the summary
        summary = text[summary_start + len("Summary:"):].strip()
        
        # Parse the key sentences into a list
        sentences = []
        
        # Split by the bullet points
        bullet_items = key_sentences_text.split("- ")
        
        # Filter out empty items and strip whitespace
        for item in bullet_items:
            item = item.strip()
            if item:
                sentences.append(item)
        
        return sentences, summary
    
    except Exception as e:
        print(f"Error parsing text: {e}")
        return [], ""
    
# Post process the generated summary
def post_process(output_text, dataset):
    if dataset == "xsum":
        sentences = nltk.sent_tokenize(output_text)
        output_text = sentences[0] if sentences else ""
    
    elif dataset == "cnn_dm":
        sentence_end_pattern = r'[。！？\.!?]'
        sentences = nltk.sent_tokenize(output_text)
        complete_sentences = []
        for sentence in sentences:
            sentence = sentence.strip()
            if re.search(sentence_end_pattern + r'$', sentence):
                complete_sentences.append(sentence)

        output_text = " ".join(complete_sentences)
    
    elif dataset == "ccsum":
        if "\n\n" in output_text:  # Remove the prompt words generated by Llama3
            output_text = output_text.split("\n\n")[-1]

    return output_text
 
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", default="mistralai/Mistral-7B-Instruct-v0.2")
    parser.add_argument("--dataset", default="xsum", type=str, help="name of the dataset to evaluate on")
    parser.add_argument("--num_samples", default=2500, type=int, help="Number of test samples to evaluate on")
    parser.add_argument("--num_sents", default=3, type=int, help="Number of attributed sentences to extract")
    parser.add_argument("--log_path", default="results/summary", type=str)
    parser.add_argument("--exp_name", type=str, help="Experiment name")
    parser.add_argument("--max_new_tokens", default=1024, type=int, help="Maximum number of tokens to generate")

    args = parser.parse_args()
    return args

def main():

    args = parse_args()
    load_dotenv(".env")
    hf_token = os.environ.get("HF_TOKEN")
    login(hf_token)
    
    # Load test dataset
    test_data = load_data(args)

    model, tokenizer = load_model_and_tokenzier(model_name=args.model_name, cache_dir="/mnt/ssd/llms")

    log_path = Path(args.log_path)
    output_path = log_path / f"{args.exp_name}_preds.json"

    processed_samples = []
    for idx, sample in tqdm(enumerate(test_data)):
        doc = sample[input_key[args.dataset]]
        prompt_template = "Extract a list of {num_sents} key sentences from the input document and then generate a one-sentence summary only based on the extracted facts: {doc}\n\nHere is the output format.\nKey Sentences:\n[- sentence1, - sentence2, ...]\nSummary:\n[summary]\n"
        prompt = prompt_template.format(num_sents=args.num_sents, 
                                        doc=doc)
        
        messages = [{"role": "user", "content": prompt}]
        raw_prompt = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        prompt_ids = tokenizer.encode(raw_prompt, add_special_tokens=False)

        input_ids = torch.tensor([prompt_ids], device=model.device)

        generate_kwargs = {
            "max_new_tokens": args.max_new_tokens,
            "do_sample": False,
            "temperature": 0.0
        }

        output_ids = model.generate(input_ids, **generate_kwargs)

        output_text = tokenizer.decode(output_ids[0, input_ids.shape[1]:], skip_special_tokens=True)
        key_sentences, summary = extract_sentences_and_summary(output_text)
        summary = post_process(summary, args.dataset)

        # Save the attributed sentences and generated summary
        attributed_sents = []
        for sent in key_sentences:
            sent = sent.strip()
            if len(sent) > 0:
                attributed_sents.append(sent)

        processed_sample = dict()
        processed_sample['id'] = sample['id']
        processed_sample[input_key[args.dataset]] = doc
        processed_sample[output_key[args.dataset]] = sample[output_key[args.dataset]]
        processed_sample.update({"attributed_sents": attributed_sents})
        processed_sample.update({"generated_summary": summary})
        processed_samples.append(processed_sample)
    
    # Save the processed instances to JSON file
    with open(output_path, 'w') as fh:
        json.dump(processed_samples, fh, indent=4)


if __name__ == "__main__":
    main()

